### ISSUE TITLE
[bug] Universe is atheist 

### ISSUE THREAD

**Issue by sethwoodworth** [alxjrvs/pathfounder-api#13]
I've been following development, and it looks like you could use a big more God(s) in your life.

Let me [show you the way](https://github.com/sethwoodworth/kneelfool/blob/master/Kneel%20Fool%20Gods.ipynb).

How and where do you want these to go?  I'm unclear where you keep your fixtures.

**Comment by sethwoodworth** [comment]
```
[{'Domains': 'Earth, Law, Nobility, Protection, Travel',
  'Name': 'Bourgwad',
  'Weapon': 'Dagger',
  'alignment': 'LN',
  'notes on imagery/story': "Dude's a real wad."},
 {'Domains': 'Healing, Knowledge, Glory, Rune, Strength',
  'Name': 'Nidalap',
  'Weapon': 'Longsword',
  'alignment': 'LN',
  'notes on imagery/story': 'stupid knight type'},
 {'Domains': 'Evil, Fire, Law, Magic, Trickery',
  'Name': 'Abaddemon',
  'Weapon': 'Whip',
  'alignment': 'LE',
  'notes on imagery/story': 'something s&m related obvs'},
 {'Domains': 'Darkness, Death, Destruction, Scalykind, War',
  'Name': 'Fafner',
  'Weapon': 'Greatsword',
  'alignment': 'LE',
  'notes on imagery/story': 'BIG EVIL DRAGON'},
```

**Comment by corincerami** [comment]
Pull requests #8 and #12 attempt to implement deities if you want to take a look.

**Comment by sethwoodworth** [comment]
Yep, I saw the PRs. I am unclear what is the correct format for rails fixtures. So I sing know how to proceed

**Comment by alxjrvs** [comment]
Those very decisions are still up in the air! 

For now, making a `gods.json` in the rules directory is a safe start.

**Comment by corincerami** [comment]
I've started this process with #14 and added all of the major deities listed [here](http://pathfinderwiki.com/wiki/Portal:Religion)

**Comment by alxjrvs** [comment]
Resolved as of https://github.com/alxjrvs/pathfounder-api/pull/14
