### ISSUE TITLE
Make a better alignment_filter

### ISSUE THREAD

**Issue by kraila** [alxjrvs/pathfounder-api#5]
e.g.:
`not: :lawful`
`must: match_deity`

**Comment by corincerami** [comment]
Pull requests #8 and #12 attempt to implement these ideas.

**Comment by corincerami** [comment]
Should probably be closed now that #8 and #12 have been merged. @alxjrvs

**Comment by alxjrvs** [comment]
Thanks for keeping me honest, Chris. :)

**Comment by corincerami** [comment]
I do what I can.
